# Generated by Django 4.2.2 on 2024-09-17 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_country_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
